"""Backend-neutral embedding specifications and runtime providers."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class EmbeddingSpec:
    """Pinned physical embedding generated by a storage connector."""

    source_column: str
    property_name: str
    model: str
    revision: str
    dimensions: int
    normalize: bool

    def __post_init__(self) -> None:
        for value, name in (
            (self.source_column, "embedding source column"),
            (self.property_name, "embedding property name"),
            (self.model, "embedding model"),
            (self.revision, "embedding revision"),
        ):
            if not isinstance(value, str) or not value:
                raise ValueError(f"{name} must be a non-empty string")
        if not isinstance(self.dimensions, int) or isinstance(
            self.dimensions, bool
        ) or self.dimensions <= 0:
            raise ValueError("embedding dimensions must be a positive integer")
        if not isinstance(self.normalize, bool):
            raise TypeError("embedding normalize must be bool")

    def to_dict(self) -> dict[str, object]:
        """Return a deterministic serializable representation."""

        return {
            "source_column": self.source_column,
            "property_name": self.property_name,
            "model": self.model,
            "revision": self.revision,
            "dimensions": self.dimensions,
            "normalize": self.normalize,
        }


def _model_contract(spec: EmbeddingSpec) -> tuple[str, str, int, bool]:
    return (spec.model, spec.revision, spec.dimensions, spec.normalize)


class EmbeddingProvider(Protocol):
    """Runtime provider for one pinned physical embedding specification."""

    def embed(self, spec: EmbeddingSpec, texts: list[str]) -> list[list[float]]:
        """Embed texts in input order."""

        ...


class SentenceTransformerEmbeddingProvider:
    """CPU sentence-transformers provider for one pinned embedding spec."""

    def __init__(
        self,
        spec: EmbeddingSpec,
        *,
        device: str = "cpu",
        dependency_extra: str = "zep",
    ) -> None:
        if not isinstance(spec, EmbeddingSpec):
            raise TypeError("embedding provider spec must be EmbeddingSpec")
        if device != "cpu":
            raise ValueError("storage embeddings are fixed to CPU")
        if not isinstance(dependency_extra, str) or not dependency_extra:
            raise ValueError("embedding dependency extra must be a non-empty string")
        try:
            from sentence_transformers import SentenceTransformer
        except ImportError as exc:
            raise ImportError(
                "sentence-transformers embeddings require the optional "
                f"{dependency_extra!r} dependency extra"
            ) from exc
        self.spec = spec
        self.device = device
        self._model = SentenceTransformer(
            spec.model,
            revision=spec.revision,
            device=device,
        )

    def embed(self, spec: EmbeddingSpec, texts: list[str]) -> list[list[float]]:
        """Embed texts with the configured pinned model."""

        if not isinstance(spec, EmbeddingSpec):
            raise TypeError("embedding request spec must be EmbeddingSpec")
        if _model_contract(spec) != _model_contract(self.spec):
            raise ValueError("embedding request does not match the configured model")
        if not all(isinstance(text, str) for text in texts):
            raise TypeError("embedding texts must be strings")
        values = self._model.encode(
            texts,
            normalize_embeddings=spec.normalize,
            convert_to_numpy=True,
            show_progress_bar=False,
        )
        return values.tolist()


__all__ = [
    "EmbeddingProvider",
    "EmbeddingSpec",
    "SentenceTransformerEmbeddingProvider",
]
